const plantes = [
  {
    "nomCommun" : "Aubépine suborbiculaire",
    "nomLatin" : "Crataegus Suborbiculata",
    "couleurBg" : "blanc",
    "image" : "https://annemoncion.com/img/illustrations/plantes/fond-transparent/aubepine_suborbiculaire.png",
    "animation": {
      "actif": false,
      "nom": "vide",
      "profondeur": 1,
    },
    "formes": {
      "actif": true,
      "type": "triangle",
      "profondeur": 1,
      "etendue": true,
      "hauteur": 500,
      "largeur": 600,
      "couleur": "#000",
      "posY": 30,
      "posX": 30,
    },
  },
  {
    "nomCommun":"Épilobe à feuilles étroites",
    "nomLatin":"Epilobium angustifolium",
    "couleurBg":"blanc",
    "image" : "https://annemoncion.com/img/illustrations/plantes/fond-transparent/epilobe_a_feuilles_etroites2.png",
    "animation": {
      "actif": true,
      "nom": "trianglesEnFile",
      "profondeur": 1,
    },
    "formes": {
      "actif": false,
      "type": "triangle",
      "profondeur": 1,
      "etendue": false,
      "hauteur": 0,
      "largeur": 0,
      "couleur": "#000",
      "posY": 50,
      "posX": 50,
    },
  },
  {
    "nomCommun":"Iris versicolore",
    "nomLatin":"Iris versicolor",
    "couleurBg":"blanc",
    "image" : "https://annemoncion.com/img/illustrations/plantes/fond-transparent/iris_versicolore.png",
    "animation": {
      "actif": true,
      "nom": "eventail",
      "profondeur": 1,
    },
    "formes": {
      "actif": false,
      "type": "triangle",
      "profondeur": 1,
      "etendue": false,
      "hauteur": 0,
      "largeur": 0,
      "couleur": "#000",
      "posY": 50,
      "posX": 50,
    },
  },
  {
    "nomCommun":"Pissenlit",
    "nomLatin":"Taraxacum officinale",
    "couleurBg":"blanc",
    "image" : "https://annemoncion.com/img/illustrations/plantes/fond-transparent/pissenlit.png",
    "animation": {
      "actif": false,
      "nom": "vide",
      "profondeur": 1,
    },
    "formes": {
      "actif": true,
      "type": "cercle",
      "profondeur": 1,
      "etendue": true,
      "hauteur": 300,
      "largeur": 300,
      "couleur": "#000",
      "posY": 50,
      "posX": 50,
    },
  },
  {
    "nomCommun":"Usnée barbue",
    "nomLatin":"Usnea barbata",
    "couleurBg":"noir",
    "image" : "https://annemoncion.com/img/illustrations/plantes/fond-transparent/usnee_barbue.png",
    "animation": {
      "actif": true,
      "nom": "hypnose",
      "profondeur": 1,
    },
    "formes": {
      "actif": true,
      "type": "triangle",
      "profondeur": 1,
      "etendue": false,
      "hauteur": 0,
      "largeur": 0,
      "couleur": "#000",
      "posY": 50,
      "posX": 50,
    },
  },
  {
    "nomCommun":"Viorne cassinoïde",
    "nomLatin":"Viburnum nudum var. cassinoides",
    "couleurBg":"blanc",
    "image" : "https://annemoncion.com/img/illustrations/plantes/fond-transparent/viorne_cassinoide.png",
    "animation": {
      "actif": false,
      "nom": "vide",
      "profondeur": 1,
    },
    "formes": {
      "actif": true,
      "type": "rectangle",
      "profondeur": 2,
      "etendue": true,
      "hauteur": 100,
      "largeur": 300,
      "couleur": "#000",
      "posY": 50,
      "posX": 50,
    },
  },
  {
    "nomCommun":"Matricaire odorante",
    "nomLatin":"Matricaria matricarioides",
    "couleurBg":"blanc",
    "image" : "https://annemoncion.com/img/illustrations/plantes/fond-transparent/matricaire_odorante.png",
    "animation": {
      "actif": true,
      "nom": "trianglesEnFile",
      "profondeur": 1,
    },
    "formes": {
      "actif": false,
      "type": "triangle",
      "profondeur": 1,
      "etendue": false,
      "hauteur": 0,
      "largeur": 0,
      "couleur": "#000",
      "posY": 50,
      "posX": 50,
    },
  },
  {
    "nomCommun":"Épinette noire",
    "nomLatin":"Picea mariana",
    "couleurBg":"noir",
    "image" : "https://annemoncion.com/img/illustrations/plantes/fond-transparent/epinette_noire.png",
    "animation": {
      "actif": true,
      "nom": "hypnose",
      "profondeur": 1,
    },
    "formes": {
      "actif": false,
      "type": "triangle",
      "profondeur": 1,
      "etendue": false,
      "hauteur": 0,
      "largeur": 0,
      "couleur": "#000",
      "posY": 50,
      "posX": 50,
    },
  },
  {
    "nomCommun":"Cerisier de Pensylvannie",
    "nomLatin":"Prunus pensylvanica",
    "couleurBg":"blanc",
    "image" : "https://annemoncion.com/img/illustrations/plantes/fond-transparent/cerisier_de_pensylvanie.png",
    "animation": {
      "actif": false,
      "nom": "vide",
      "profondeur": 1,
    },
    "formes": {
      "actif": true,
      "type": "rectangle",
      "profondeur": 1,
      "etendue": true,
      "hauteur": 200,
      "largeur": 200,
      "couleur": "#000",
      "posY": 50,
      "posX": 50,
    },
  },
  {
    "nomCommun":"Bleuetier",
    "nomLatin":"Vaccinium angustifolium",
    "couleurBg":"blanc",
    "image" : "https://annemoncion.com/img/illustrations/plantes/fond-transparent/bleuetier.png",
    "animation": {
      "actif": true,
      "nom": "eventail",
      "profondeur": 1,
    },
    "formes": {
      "actif": false,
      "type": "triangle",
      "profondeur": 1,
      "etendue": false,
      "hauteur": 0,
      "largeur": 0,
      "couleur": "#000",
      "posY": 50,
      "posX": 50,
    },
  },
]

module.exports = {
  plantes
};