import { Forfait } from './forfait';
import { HOTELS } from './mock-hotels';

export const FORFAITS: Forfait[] = [
    { id: '1',
      destination: 'Toronto',
      villeDepart: 'Montréal',
      hotel: HOTELS[0],
      dateDepart: new Date('2020-11-01'),
      dateRetour: new Date('2020-11-07'),
      prix: 749,
      rabais: 350,
      forfaitVedette: true,
    },
    { id: '2',
      destination: 'Gaspé',
      villeDepart: 'Montréal',
      hotel: HOTELS[1],
      dateDepart: new Date('2020-11-01'),
      dateRetour: new Date('2020-11-10'),
      prix: 2056,
      rabais: 0,
      forfaitVedette: false,
    },
    { id: '3',
      destination: 'Montréal',
      villeDepart: 'Montréal',
      hotel: HOTELS[2],
      dateDepart: new Date('2020-11-01'),
      dateRetour: new Date('2020-11-14'),
      prix: 899,
      rabais: 125,
      forfaitVedette: false,
    },
    { id: '4',
      destination: 'Floride',
      villeDepart: 'Montréal',
      hotel: HOTELS[3],
      dateDepart: new Date('2020-11-01'),
      dateRetour: new Date('2020-11-07'),
      prix: 2030,
      rabais: 0,
      forfaitVedette: false,
    },
    { id: '5',
      destination: 'Paris',
      villeDepart: 'Montréal',
      hotel: HOTELS[4],
      dateDepart: new Date('2020-11-01'),
      dateRetour: new Date('2020-11-10'),
      prix: 3009,
      rabais: 0,
      forfaitVedette: false,
    },
    { id: '6',
      destination: 'Paris',
      villeDepart: 'Montréal',
      hotel: HOTELS[0],
      dateDepart: new Date('2020-11-01'),
      dateRetour: new Date('2020-11-14'),
      prix: 578,
      rabais: 0,
      forfaitVedette: false,
    },
    { id: '7',
      destination: 'Paris',
      villeDepart: 'Montréal',
      hotel: HOTELS[1],
      dateDepart: new Date('2020-11-01'),
      dateRetour: new Date('2020-11-07'),
      prix: 990,
      rabais: 0,
      forfaitVedette: false,
    },
    { id: '8',
      destination: 'Nice',
      villeDepart: 'Montréal',
      hotel: HOTELS[2],
      dateDepart: new Date('2020-11-01'),
      dateRetour: new Date('2020-11-10'),
      prix: 999,
      rabais: 199,
      forfaitVedette: true,
    },
    { id: '9',
      destination: 'Toulouse',
      villeDepart: 'Montréal',
      hotel: HOTELS[3],
      dateDepart: new Date('2020-11-01'),
      dateRetour: new Date('2020-11-14'),
      prix: 699,
      rabais: 0,
      forfaitVedette: false,
    }
];
